name: Deploy & Run Databricks Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-run-databricks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Databricks CLI & dbx
        run: |
          pip install databricks-cli dbx

      - name: Configure Databricks CLI
        run: |
          databricks configure --host ${{ secrets.DATABRICKS_HOST }} --token ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy Databricks Workflow
        run: |
          dbx deploy --jobs=workflow.yaml

      - name: Trigger Databricks Workflow
        run: |
          dbx launch "NYC Restaurant Analytics Pipeline"
